export const SET_THEME = "SET_THEME";
export const SET_SYSTEM_THEME = "SET_SYSTEM_THEME";
export const SET_SYSTEM_BIOMETRIC = "SET_SYSTEM_BIOMETRIC";
export const SET_EMAIL_VERIFY = "SET_EMAIL_VERIFY";
export const SET_USER = "SET_USER";
